travis

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -1,3 +1,9 @@
+#!/usr/bin/env bash
+set -e # halt script on error
+
+bundle exec jekyll build
+touch ./_site/.nojekyll # this file tells gh-pages that there is no need to build
+
 #!/bin/sh
 
 set -e
@@ -7,5 +13,3 @@ bundle exec htmlproofer ./_site --check-html --check-sri
 bundle exec rubocop -D --config .rubocop.yml
 bundle exec script/validate-html
 gem build jekyll-theme-minimal.gemspec
-bundle exec jekyll build
-touch ./_site/.nojekyll # this file tells gh-pages that there is no need to build
